# Build stage: full install (Prisma client is generated by postinstall), bundle,
# then drop devDependencies while keeping the generated client.
FROM node:22-slim AS build

WORKDIR /app

COPY package.json package-lock.json prisma.config.ts ./
COPY prisma/ ./prisma/
RUN npm ci

COPY tsconfig.json vite.config.ts ./
COPY src/ ./src/
RUN npm run build && npm prune --omit=dev

# Runtime stage: production dependencies and the bundle only, as a non-root user.
FROM node:22-slim

ENV NODE_ENV=production
WORKDIR /app

COPY --from=build /app/package.json ./
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
# Schema + migrations so `npx prisma migrate deploy` can run in the container
# when DATABASE_URL enables the REST API.
COPY --from=build /app/prisma.config.ts ./
COPY --from=build /app/prisma ./prisma

USER node
EXPOSE 3535

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD node -e "fetch('http://127.0.0.1:'+(process.env.PORT||3535)+'/healthz').then(r=>process.exit(r.ok?0:1),()=>process.exit(1))"

CMD ["node", "dist/index.js"]
